/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.codegen;


import edu.java.domain.jooq.codegen.tables.Chat;
import edu.java.domain.jooq.codegen.tables.Link;
import edu.java.domain.jooq.codegen.tables.Linkschats;
import edu.java.domain.jooq.codegen.tables.records.ChatRecord;
import edu.java.domain.jooq.codegen.tables.records.LinkRecord;
import edu.java.domain.jooq.codegen.tables.records.LinkschatsRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] { Chat.CHAT.TG_CHAT_ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] { Link.LINK.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinkschatsRecord, LinkRecord> CONSTRAINT_8 = Internal.createForeignKey(Linkschats.LINKSCHATS, DSL.name("CONSTRAINT_8"), new TableField[] { Linkschats.LINKSCHATS.URL_ID }, Keys.CONSTRAINT_23, new TableField[] { Link.LINK.ID }, true);
    public static final ForeignKey<LinkschatsRecord, ChatRecord> CONSTRAINT_84 = Internal.createForeignKey(Linkschats.LINKSCHATS, DSL.name("CONSTRAINT_84"), new TableField[] { Linkschats.LINKSCHATS.TG_CHAT_ID }, Keys.CONSTRAINT_1, new TableField[] { Chat.CHAT.TG_CHAT_ID }, true);
}
