app:
  scheduler:
    enable: true
    interval: 12000
    force-check-delay: 12000

spring:
  application:
    name: scrapper

server:
  port: 8080
  baseURL: http://localhost:${server.port}}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    path: /swagger-ui
