app:
  scheduler:
    enable: true
    interval: 20000
    force-check-delay: 60

spring:
  application:
    name: scrapper
  liquibase:
    enabled: off
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

http-client:
  port: 8090
  baseURL: http://localhost:${http-client.port}}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    path: /swagger-ui


