app:
  telegram-token: unset

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

http-client:
  port: 8080
  baseURL: http://localhost:${http-client.port}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    path: /swagger-ui
