/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.entity.tables.records;


import edu.java.domain.jooq.entity.tables.Linkschats;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkschatsRecord extends TableRecordImpl<LinkschatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKSCHATS.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKSCHATS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINKSCHATS.URL_ID</code>.
     */
    public void setUrlId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKSCHATS.URL_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getUrlId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>LINKSCHATS.TG_CHAT_ID</code>.
     */
    public void setTgChatId(@NotNull Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINKSCHATS.TG_CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChatId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkschatsRecord
     */
    public LinkschatsRecord() {
        super(Linkschats.LINKSCHATS);
    }

    /**
     * Create a detached, initialised LinkschatsRecord
     */
    @ConstructorProperties({ "id", "urlId", "tgChatId" })
    public LinkschatsRecord(@Nullable Long id, @NotNull Long urlId, @NotNull Long tgChatId) {
        super(Linkschats.LINKSCHATS);

        setId(id);
        setUrlId(urlId);
        setTgChatId(tgChatId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinkschatsRecord
     */
    public LinkschatsRecord(edu.java.domain.jooq.entity.tables.pojos.Linkschats value) {
        super(Linkschats.LINKSCHATS);

        if (value != null) {
            setId(value.getId());
            setUrlId(value.getUrlId());
            setTgChatId(value.getTgChatId());
            resetChangedOnNotNull();
        }
    }
}
