/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.codegen.tables;


import edu.java.domain.jooq.codegen.DefaultSchema;
import edu.java.domain.jooq.codegen.Keys;
import edu.java.domain.jooq.codegen.tables.records.LinkschatsRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Linkschats extends TableImpl<LinkschatsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINKSCHATS</code>
     */
    public static final Linkschats LINKSCHATS = new Linkschats();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<LinkschatsRecord> getRecordType() {
        return LinkschatsRecord.class;
    }

    /**
     * The column <code>LINKSCHATS.ID</code>.
     */
    public final TableField<LinkschatsRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>LINKSCHATS.URL_ID</code>.
     */
    public final TableField<LinkschatsRecord, Long> URL_ID = createField(DSL.name("URL_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LINKSCHATS.TG_CHAT_ID</code>.
     */
    public final TableField<LinkschatsRecord, Long> TG_CHAT_ID = createField(DSL.name("TG_CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private Linkschats(Name alias, Table<LinkschatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Linkschats(Name alias, Table<LinkschatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINKSCHATS</code> table reference
     */
    public Linkschats(String alias) {
        this(DSL.name(alias), LINKSCHATS);
    }

    /**
     * Create an aliased <code>LINKSCHATS</code> table reference
     */
    public Linkschats(Name alias) {
        this(alias, LINKSCHATS);
    }

    /**
     * Create a <code>LINKSCHATS</code> table reference
     */
    public Linkschats() {
        this(DSL.name("LINKSCHATS"), null);
    }

    public <O extends Record> Linkschats(Table<O> child, ForeignKey<O, LinkschatsRecord> key) {
        super(child, key, LINKSCHATS);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<LinkschatsRecord, Long> getIdentity() {
        return (Identity<LinkschatsRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public List<ForeignKey<LinkschatsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_8, Keys.CONSTRAINT_84);
    }

    private transient Link _link;
    private transient Chat _chat;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_8);

        return _link;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null)
            _chat = new Chat(this, Keys.CONSTRAINT_84);

        return _chat;
    }

    @Override
    @NotNull
    public Linkschats as(String alias) {
        return new Linkschats(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Linkschats as(Name alias) {
        return new Linkschats(alias, this);
    }

    @Override
    @NotNull
    public Linkschats as(Table<?> alias) {
        return new Linkschats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Linkschats rename(String name) {
        return new Linkschats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Linkschats rename(Name name) {
        return new Linkschats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Linkschats rename(Table<?> name) {
        return new Linkschats(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
