/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.codegen.tables.records;


import edu.java.domain.jooq.codegen.tables.Linkschats;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkschatsRecord extends TableRecordImpl<LinkschatsRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKSCHATS.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKSCHATS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINKSCHATS.URL_ID</code>.
     */
    public void setUrlId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKSCHATS.URL_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getUrlId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>LINKSCHATS.TG_CHAT_ID</code>.
     */
    public void setTgChatId(@NotNull Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINKSCHATS.TG_CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChatId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Linkschats.LINKSCHATS.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return Linkschats.LINKSCHATS.URL_ID;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return Linkschats.LINKSCHATS.TG_CHAT_ID;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getUrlId();
    }

    @Override
    @NotNull
    public Long component3() {
        return getTgChatId();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getUrlId();
    }

    @Override
    @NotNull
    public Long value3() {
        return getTgChatId();
    }

    @Override
    @NotNull
    public LinkschatsRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkschatsRecord value2(@NotNull Long value) {
        setUrlId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkschatsRecord value3(@NotNull Long value) {
        setTgChatId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkschatsRecord values(@Nullable Long value1, @NotNull Long value2, @NotNull Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkschatsRecord
     */
    public LinkschatsRecord() {
        super(Linkschats.LINKSCHATS);
    }

    /**
     * Create a detached, initialised LinkschatsRecord
     */
    @ConstructorProperties({ "id", "urlId", "tgChatId" })
    public LinkschatsRecord(@Nullable Long id, @NotNull Long urlId, @NotNull Long tgChatId) {
        super(Linkschats.LINKSCHATS);

        setId(id);
        setUrlId(urlId);
        setTgChatId(tgChatId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinkschatsRecord
     */
    public LinkschatsRecord(edu.java.domain.jooq.codegen.tables.pojos.Linkschats value) {
        super(Linkschats.LINKSCHATS);

        if (value != null) {
            setId(value.getId());
            setUrlId(value.getUrlId());
            setTgChatId(value.getTgChatId());
            resetChangedOnNotNull();
        }
    }
}
